### ISSUE TITLE
src 디렉토리 구성

### ISSUE THREAD

**Issue by Unperknown** [Unperknown/AINOMOK#12]
앞으로 저번에 계속 작성하고 있었던 소스 파일들을 올리려고 합니다. 그런데 src 디렉토리 안이 현재 이렇게 구성되어 있는데
```
src /
   AINOMOK /
        Arduino /
        Image_Processing /
        Q-Learning Omok /
        x64 /
        나머지 Visual Studio 구동에 필요한 파일들
   AINOMOK.sin -> 솔루션 파일
```
지금 생각해보니 굳이 Visual Studio 라이브러리 구성에 얽매일 필요 없이 Python module로 바꾸는 것이 더 좋을 것 같습니다. 그래서 제가 추천하고자 하는 방식은
```
unittests.py
src /
    Game.py
    Board.py
    Player.py
    Computer.py
    detection /
         detectStone.py
         sendUpdate.py
    ai /
        SSS.py
    arduino /
        ???.cpp
```
이와 같습니다. 이에 대해서 리뷰를 남겨주시고 토의한 방식대로 master branch에 올리도록 하겠습니다. 파일 충돌을 막기 위해 올리고 나면 자신의 branch에 있는 디렉토리를 조정하시기 바랍니다.

**Comment by asphalt-alpha** [comment]
파이썬 프로젝트와 아두이노 간의 시리얼 통신도 가능하니 이렇게 진행 하셔도 될 것 같습니다.

**Comment by Unperknown** [comment]
바꿀 때 일어날 리스크가 없는 것으로 알겠습니다. ohseyoung123의 의견까지 들은 다음에 위에서 제안한 방식대로 src 디렉토리 구성을 바꾸도록 하겠습니다. 위에서 강조했던 대로 자신의 branch에 업데이트해주시기 바랍니다.

**Comment by ohseyoung123** [comment]
동의합니다.
