### ISSUE TITLE
바둑판 영상처리 반환 데이터 전송 문제

### ISSUE THREAD

**Issue by Unperknown** [Unperknown/AINOMOK#9]
현재 OpenCV Python API로 바둑판 이미지의 각 픽셀의 색 값을 분석하여 검은 돌의 위치와 하얀 돌의 위치를 판별하여 최종적으로 바둑판 상태를 변경하는 프로세스를 구현하고 있습니다.

그런데 웹캠을 설치하는데 데스크탑과의 연결이 잘 되는지 궁금합니다. 만약 그렇지 않으면 이미지를 전송하는 데 필요한 통신을 따로 구현해야 해서 이 부분에 대해서 답변해주시기 바랍니다.

**Comment by asphalt-alpha** [comment]
컴퓨터와 웹캠을 usb로 연결할겁니다.
